name: MortisMachines
version: '${project.version}'
main: me.none030.mortismachines.MortisMachines
api-version: 1.13
depend:
  - ProtocolLib
softdepend:
  - Towny
  - MortisHoppers
commands:
  machine:
    aliases: [machines, mortismachine, mortismachines]
